### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by gboehl** [mfschubert/sparsejac#1]
This is actually great functionallity! 

I understand that this is still work in progress, but would it possible to publish a beta release on PyPI?

I would like to use it experimentally within one of my packages.

**Comment by mfschubert** [comment]
Hi @gboehl, @peterdsharpe, sorry for the long silence. I opened up some bandwidth for this type of work and took a crack at it. Hope it works for you and feel free to raise issues if you encounter them.
